In [1]:
import numpy as np

In [2]:
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [3]:
type(data)

numpy.ndarray

In [11]:
## 차원 : 이미지, 음성, 데이터를 저장하는 구조
# 이미지 : 2차원 // 동영상 : 3차원
data1 = np.array([1,2,3,4,5])
data2 = np.array([[1,2,3],
                  [4,5,6]]
                  )

In [12]:
data1.ndim, data2.ndim

(1, 2)

In [14]:
# 몇 개의 요소로 구성되어 있는지
data1.shape

(5,)

In [15]:
data2.shape

(2, 3)

In [19]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [21]:
# 변수형을 바꾸고 싶을 때
arr = np.array([1,2,3,4,5], dtype="float")
arr.dtype

dtype('float64')

In [24]:
arr = np.array([1,2,3,4,5])
arr = arr.astype("float") # arr.astype("float") 만 쓰면 바뀌지 않음.
arr.dtype

dtype('float64')

In [28]:
## 행열 교환
arr = np.array([[1,2,3],[4,5,6]])
new_arr = arr.T
new_arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
## reshape --> 원본이 바뀌지 않고 바뀐 배열을 반환한다.
arr = np.array([[1,2,3],[4,5,6]])
arr.shape # --> 3*2 행렬로
new_arr1 = arr.reshape((3,2))
new_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
## resize --> 원본이 바뀐다
arr = np.array([[1,2,3],[4,5,6]])
arr.resize((3,2))
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
## 쉽게 만들기
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [44]:
## zeros --> 데이터가 정해져 있을 때(0) ( 크기가 고정되어 있을 때) 
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
## ones --> 데이터가 정해져 있을 때(1) ( 크기가 고정되어 있을 때) 
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
## ones --> 데이터가 정해져 있을 때(fill_value = ?) ( 크기가 고정되어 있을 때) 
arr = np.full((3,3),fill_value=5)
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [53]:
## eye 대각선으로
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
arr = np.array([1,2],["a"])
arr

TypeError: Field elements must be 2- or 3-tuples, got ''a''

In [57]:
np.random.rand(5) # 0~1 랜덤

array([0.6443602 , 0.60190038, 0.42619057, 0.36386404, 0.17087307])

In [58]:
np.random.randn(5) # 가우시안 정규 분포 랜덤

array([1.33477709, 0.18371714, 0.57662751, 1.1774587 , 0.59807708])

In [62]:
np.random.randint(1,10,3) # 지정 범위 균일 분포 랜덤

array([1, 3, 8])

In [66]:
arr = np.arange(1,20,3)
arr_copy = arr.copy()
np.random.shuffle(arr)

In [67]:
arr

array([16, 19, 13,  1,  7,  4, 10])

In [68]:
arr_copy

array([ 1,  4,  7, 10, 13, 16, 19])

### 연산

In [71]:
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)

In [72]:
arr1, arr2

(array([1, 2, 3]), array([4, 5, 6]))

In [77]:
arr1 + arr2 # 같은 인덱스끼리 더함

array([5, 7, 9])

In [78]:
arr1*arr2 # 같은 인덱스끼리 곱함

array([ 4, 10, 18])

In [79]:
arr1/arr2 #같은 인덱스끼리 나눔

array([0.25, 0.4 , 0.5 ])